# From 'openshift-applier'
- src: https://github.com/redhat-cop/openshift-applier
  version: v2.1.2
# From 'openshift-labels'
- src: https://github.com/redhat-cop/casl-ansible.git
  version: v3.11.4

# Get the roles under development
- src: https://github.com/westdart/ar_osc_amqbroker.git

# Get the roles under development
- src: https://github.com/westdart/ar_osc_amqinterconnect.git

# Get the roles under development
- src: https://github.com/westdart/ar_osc_aspera.git

