aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Test role.
    openshift.io/reconcile-protect: "false"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: testrole
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch


- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "pvc-${APPLICATION_NAME}-${PVC_ENV}"
  spec:
    storageClassName: nfs-standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 500Mi


        volumeName: "pv-${APPLICATION_NAME}-${PVC_ENV}"
        volumeMounts:
          - mountPath: /dif-router
            name: "vol-${APPLICATION_NAME}"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext:
          supplementalGroups: [1000310000]
        terminationGracePeriodSeconds: 30
        volumes:
        - name: "vol-${APPLICATION_NAME}"
          persistentVolumeClaim:
            claimName: "pvc-${APPLICATION_NAME}-${PVC_ENV}"
