---
- name: Add Registry Secret to namespace
  hosts: localhost

  vars:

  tasks:
    - name: Login to Registry Openshift to obtain token if Registry is running under Openshift
      include_role:
        name: ar_osc_common_templates
        tasks_from: login
      vars:
        ar_osc_common_templates_openshift_login_url: "{{ registry_login_credentials[registry_server].openshift_url }}"
        ar_osc_common_templates_openshift_username: "{{ registry_login_credentials[registry_server].username }}"
        ar_osc_common_templates_openshift_password: "{{ registry_login_credentials[registry_server].password }}"
      when: "'openshift_url' in registry_login_credentials[registry_server]"

    - name: Obtain the Openshift Token
      command: oc whoami -t
      register: oc_token_result
      changed_when: false
      when: "'openshift_url' in registry_login_credentials[registry_server]"

    - set_fact:
        _password: "{{ oc_token_result.stdout }}"
      when: "'openshift_url' in registry_login_credentials[registry_server]"

    - set_fact:
        _password: "{{ registry_login_credentials[registry_server].password }}"
      when: "'openshift_url' not in registry_login_credentials[registry_server] and 'password' in registry_login_credentials[registry_server]"

    - set_fact:
        _token: "{{ registry_login_credentials[registry_server].token }}"
      when: "'token' in registry_login_credentials[registry_server]"

    - name: "Assert OpenShift Login URL provided"
      assert:
        that:
          - "oc_login_url is defined"

    - name: Login to target OpenShift
      include_role:
        name: ar_osc_common_templates
        tasks_from: login
      vars:
        ar_osc_common_templates_openshift_login_force: true
        ar_osc_common_templates_openshift_login_url: "{{ oc_login_url }}"
        ar_osc_common_templates_openshift_username: "{{ openshift_login_credentials[oc_login_url].openshift_user }}"
        ar_osc_common_templates_openshift_password: "{{ openshift_login_credentials[oc_login_url].openshift_password | default('') }}"
        ar_osc_common_templates_openshift_token: "{{ openshift_login_credentials[oc_login_url].openshift_token | default('') }}"

    - name: Include common role to add registry secret
      include_role:
        name: ar_osc_common_templates
        tasks_from: registry-secret
      vars:
        ar_osc_common_templates_registry_secret_name: "{{ registry_login_credentials[registry_server].secret_name | default(registry_secret_name) }}"
        ar_osc_common_templates_registry_secret_namespace: "{{ registry_secret_namespace }}"
        ar_osc_common_templates_registry_server: "{{ registry_server }}"
        ar_osc_common_templates_registry_username: "{{ registry_login_credentials[registry_server].username }}"
        ar_osc_common_templates_registry_password: "{{ _password | default('') }}"
        ar_osc_common_templates_registry_token: "{{ _token | default('') }}"
        ar_osc_common_templates_registry_email: "{{ registry_login_credentials[registry_server].email | default('') }}"
