---
- name: Deploy Aspera Containers
  hosts: localhost

  vars:
    target_app_instance_names: "{{ targets | default(app_instances | json_query('[*].name')) }}"
    target_app_instances: "{{ app_instances | select_from_array_of_dicts('name', target_app_instance_names) }}"

  vars_files:
    - "{{ amq_interconnect_instances_file }}"
    - "{{ amq_secrets_file | default(generated_config_dir + '/mjdi.vault') }}"

  tasks:
    ####################################################################################################################
    - name: "Generate the aspera config for each instance"
      include_role:
        name: aspera_config
      vars:
        aspera_config_name:             "{{ aspera_instance.name }}"
        aspera_config_ssh_port:         "{{ aspera_config_sshd_internal_port }}"
        aspera_config_dest:             "{{ generated_config_dir }}"
        aspera_config_k8s_template:     "{{ aspera_template }}"
        aspera_config_docker_registry:  "{{ docker_registry }}"
        aspera_config_package_base_url: "{{ package_repository }}"
      when: "aspera_instance.incomingAddressList | length > 0"
      with_items:
        - "{{ target_app_instances }}"
      loop_control:
        loop_var: aspera_instance
